<?php

namespace IB\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getApplicationsWithAdvert($limit)
	{
		$qb = $this->createQueryBuilder('a');
		$qb
     	 ->innerJoin('a.advert', 'adv')
      	 ->addSelect('adv')
      	 ->orderby('a.date','DESC')
      	 ->setMaxResults($limit);  	// On prend les $limit plus récentes

      	 // Enfin, on retourne le résultat
   	 	return $qb
      	 ->getQuery()
      	 ->getResult();
	}
}
